CREATE TABLE IF NOT EXISTS cells (
	cellID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	name TEXT NOT NULL,
	PRIMARY KEY (cellID)
);

CREATE TABLE IF NOT EXISTS links (
	linkID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	linkType ENUM('LINK', 'DLINK') NOT NULL,
	source TEXT NOT NULL,
	sourceID INT UNSIGNED NOT NULL,
	target TEXT NOT NULL,
	targetID INT UNSIGNED NOT NULL,
	PRIMARY KEY (linkID)
);
