CREATE TABLE IF NOT EXISTS cells (
	cellID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	name TEXT NOT NULL,
	PRIMARY KEY (cellID)
);

CREATE TABLE IF NOT EXISTS links (
	linkID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	linkType ENUM('LINK', 'DLINK') NOT NULL,
	cellLeft TEXT NOT NULL,
	cellLeftID INT UNSIGNED NOT NULL,
	cellRight TEXT NOT NULL,
	cellRightID INT UNSIGNED NOT NULL,
	PRIMARY KEY (linkID)
);
